import {
    FASTDesignSystemProvider,
    FASTCard,
    FASTButton,
    FASTAccordion,
    FASTAnchor,
    FASTAccordionItem,
    FASTBadge,
    FASTCheckbox,
    FASTDesignSystem,
    FASTDialog,
    FASTDivider,
    FASTFlipper,
    FASTMenu,
    FASTMenuItem,
    FASTProgress,
    FASTProgressRing,
    FASTRadio,
    FASTRadioGroup,
    FASTSlider,
    FASTSliderLabel,
    FASTSwitch,
    FASTTab,
    FASTTabPanel,
    FASTTabs,
    FASTTextArea,
    FASTTextField,
    FASTTreeItem,
    FASTTreeView,
} from '@microsoft/fast-components';

/*
 * Ensure that tree-shaking doesn't remove these components from the bundle.
 * There are multiple ways to prevent tree shaking, of which this is one.
 */
FASTDesignSystemProvider;
FASTCard;
FASTButton;
FASTAccordion;
FASTAnchor;
FASTAccordionItem;
FASTBadge;
FASTCheckbox;
FASTDialog;
FASTDivider;
FASTFlipper;
FASTMenu;
FASTMenuItem;
FASTProgress;
FASTProgressRing;
FASTRadio;
FASTRadioGroup;
FASTSlider;
FASTSliderLabel;
FASTSwitch;
FASTTab;
FASTTabPanel;
FASTTabs;
FASTTextArea;
FASTTextField;
FASTTreeItem;
FASTTreeView;
