
###


POST http://localhost:7071/api/CreateHero HTTP/1.1
Content-Type: application/json

{
    "name": "Hulk",
    "team": "Avengers",
    "universe": "Marvel",
    "superPowers": [],
    "avatarUrl": "https://avatarfiles.alphacoders.com/121/thumb-121988.png"
}

###


POST http://localhost:7071/api/UpdateHero HTTP/1.1
Content-Type: application/json

{
    "id": "87b0f9ff-2844-4f93-8e99-8cefdd72632c",
    "name": "Thor Odinson",
    "team": "Avengers",
    "universe": "Marvel",
    "superPowers": [
      "God",
      "Thunder",
      "Mjölnir",
      "Stormbreaker"
    ],
    "avatarUrl": "https://store.playstation.com/store/api/chihiro/00_09_000/container/GB/en/999/EP0331-CUSA04584_00-AV00000000000026/1597151538000/image?w=240&h=240&bg_color=000000&opacity=100&_version=00_09_000",
    "created": "2020-09-14T03:12:26.694+00:00",
    "updated": null
  }

###


DELETE http://localhost:7071/api/DeleteHero?id=dd254149-61e8-41f1-8b06-1d84e240ff36&partition=Hulk HTTP/1.1
Content-Type: application/json


###


GET http://localhost:7071/api/ListHeros HTTP/1.1
Content-Type: application/json


###

POST http://localhost:7071/api/ImportHeros?id=1&id=2,3&id=70,71,72&id=80,81,82&id=180,181,182&id=300,301,302&id=345,346,347&id=422,423,424&id=515,496,289&id=578,579,580&id=667,668,669&id=719,720,708,697,686  HTTP/1.1
Content-Type: application/json


###


POST http://localhost:7071/api/RandomHeros?count=20  HTTP/1.1
Content-Type: application/json


###

POST http://localhost:7071/api/ClearHeros
Content-Type: application/json

